# Generated by Django 5.0 on 2024-01-31 10:14

import apps.recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.recipe.models.recipe_image_file_path),
        ),
    ]
